name: flutter_clean_architecture
description: A Flutter package that implements the Clean Architecture by Uncle Bob in Flutter. It provides classes that can be extended and used as Views, Controllers, Presenters, Observers, and UseCases. The rest of the Clean Architecture folder setup is included in the example.
version: 0.0.1
author: Shady Boukhary <sb199898.sb@gmail.com>
homepage: https://github.com/ShadyBoukhary/flutter_clean_architecture

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
  rxdart: ^0.20.0
  logging: ^0.11.3+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

flutter:
