name: flutter_clean_architecture
description: A Flutter package that implements the Clean Architecture by Uncle Bob in Flutter. It provides Views, Controllers, Presenters, Observers, and UseCases.
version: 4.0.4
author: Shady Boukhary <sb199898.sb@gmail.com>
homepage: https://github.com/ShadyBoukhary/flutter_clean_architecture

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  meta: ^1.3.0-nullsafety.3
  provider: ^4.3.2+3
  responsive_builder: ^0.3.0
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety.5
  pedantic: ^1.10.0-nullsafety.2

flutter:
