name: flutter_clean_architecture
description: A Flutter package that implements the Clean Architecture by Uncle Bob in Flutter. It provides Views, Controllers, Presenters, Observers, and UseCases.
version: 1.0.7
author: Shady Boukhary <sb199898.sb@gmail.com>
homepage: https://github.com/ShadyBoukhary/flutter_clean_architecture

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  rxdart: ^0.22.2
  logging: ^0.11.3+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

flutter:
